spring:
  application:
    name: lesson-application
  jpa:
    database postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
      url: jdbc:postgresql://localhost:5432/lesson_application
      username: mick
        password: mick
        platform: postgres
        driver-class-name: org.postgresql.Driver

server:
  port: 0
  servlet:
    context-path: /lesson-application/

kafka:
  server: http://localhost:9092
  groupId: chemistry-lesson.1