spring:
  application:
    name: chat-application
  jpa:
    database: postgresql
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/chat
    username: mick
    password: mick
    platform: postgres
    driver-class-name: org.postgresql.Driver

flyway:
  url: jdbc:postgresql://localhost:5432/chat
  schemas: public
  user: mick
  password: mick
  baselineOnMigrate: true
  locations: classpath:db.migration

server:
  port: 8100
  servlet:
    context-path: /chat-application

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/