spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/chemfixedanswer
    username: mick
    password: mick
    platform: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    locations: classpath:db.migration

server:
  port: 0
  servlet:
    context-path: /tasks-chemfixedanswer-application/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

kafka:
  server: http://localhost:9092
  groupId: fixed-answer-task.1
