spring:
  application:
    name: chemequations-application
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/chemequations
    username: mick
    password: mick
    platform: postgres
    driver-class-name: org.postgresql.Driver

server:
  port: 9090
  servlet:
    context-path: /chemequations-application/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

kafka:
  server: http://localhost:9092
  groupId: equations-task.1

#Тестируем добавление файла в мастер
#создали новую ветку